"use client";

import { CalendarDays, DollarSign, Loader2, Save, TrendingDown, TrendingUp } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { useAuth } from "@/context/AuthContext";
import { getDailyEntriesInRange, getDailyRevenue, saveDailyRevenue } from "@/lib/firestore-helpers";
import { formatCurrency } from "@/lib/utils";
import type { DailyEntry } from "@/types";

const dayKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const dayBounds = (day: string) => { const [year = 1970, month = 1, date = 1] = day.split("-").map(Number); return { start: new Date(year, month - 1, date).getTime(), end: new Date(year, month - 1, date + 1).getTime() - 1 }; };

export default function DailyRevenuePage() {
  const { user, profile, loading } = useAuth(); const router = useRouter(); const [day, setDay] = useState(() => dayKey(new Date())); const [entries, setEntries] = useState<DailyEntry[]>([]); const [usd, setUsd] = useState(""); const [rate, setRate] = useState("1600"); const [note, setNote] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [fetching, setFetching] = useState(true);
  useEffect(() => { if (!loading && !user) router.replace("/login"); }, [loading, user, router]);
  useEffect(() => { if (profile && profile.role !== "super_admin") router.replace("/dashboard"); }, [profile, router]);
  useEffect(() => { if (!user || profile?.role !== "super_admin") return; setFetching(true); const bounds = dayBounds(day); Promise.all([getDailyEntriesInRange(bounds.start, bounds.end), getDailyRevenue(day)]).then(([daily, revenue]) => { setEntries(daily); setUsd(revenue ? String(revenue.revenueUsd) : ""); setRate(revenue ? String(revenue.exchangeRate) : "1600"); setNote(revenue?.note || ""); }).finally(() => setFetching(false)); }, [user, profile?.role, day]);
  const spent = useMemo(() => entries.reduce((total, entry) => total + entry.spend, 0), [entries]); const revenueNgn = (Number(usd) || 0) * (Number(rate) || 0); const result = revenueNgn - spent;
  async function save() { setBusy(true); setMessage(""); try { await saveDailyRevenue({ day, revenueUsd: Number(usd), exchangeRate: Number(rate), note }); setMessage("Daily revenue saved. Your comparison is now up to date."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save daily revenue."); } finally { setBusy(false); } }
  if (loading || !user || !profile) return <main className="flex min-h-screen items-center justify-center bg-navy"><Loader2 className="animate-spin text-white" /></main>;
  return <AppShell><div className="mx-auto max-w-5xl space-y-6 px-4 py-5 sm:px-6 sm:py-7"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Daily business signal</p><h1 className="mt-1 font-display text-2xl font-extrabold tracking-tight text-ink">Revenue vs ad spend</h1><p className="mt-1 max-w-2xl text-sm text-ink-soft">Log AdSense revenue in USD, set the day’s exchange rate, and compare it against the actual naira spend already recorded by your ads accounts.</p></div><label className="app-surface flex items-center gap-2 px-3 py-2.5 text-sm font-semibold text-ink"><CalendarDays size={16} className="text-primary" /><input type="date" value={day} onChange={(event) => setDay(event.target.value)} className="bg-transparent outline-none" /></label></header>
    <section className="grid gap-3 sm:grid-cols-3"><Metric icon={TrendingDown} label="Ad spend" value={formatCurrency(spent)} tone="text-danger" /><Metric icon={DollarSign} label="AdSense revenue" value={formatCurrency(revenueNgn)} sub={`${Number(usd || 0).toLocaleString()} USD`} tone="text-primary" /><Metric icon={result >= 0 ? TrendingUp : TrendingDown} label={result >= 0 ? "Net positive" : "Net negative"} value={formatCurrency(result)} tone={result >= 0 ? "text-success" : "text-danger"} /></section>
    <section className="app-surface grid gap-6 p-5 sm:p-6 lg:grid-cols-[1fr_.85fr]"><div><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary-soft text-primary"><DollarSign size={18} /></span><div><h2 className="font-display text-lg font-bold text-ink">Record AdSense revenue</h2><p className="text-xs text-ink-soft">Only the revenue is entered manually; spend is pulled from the daily logs.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="AdSense revenue (USD)"><input inputMode="decimal" value={usd} onChange={(event) => setUsd(event.target.value)} placeholder="0.00" className="field" /></Field><Field label="USD to NGN rate"><input inputMode="decimal" value={rate} onChange={(event) => setRate(event.target.value)} placeholder="1600" className="field" /></Field></div><Field label="Note (optional)"><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="For example: AdSense earnings for the day" className="field mt-1 min-h-24 resize-y" /></Field><button disabled={busy || !usd || !rate} onClick={save} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-white shadow-[0_8px_18px_rgba(0,81,207,.20)] transition hover:-translate-y-0.5 hover:bg-primary-hover disabled:cursor-not-allowed disabled:opacity-50"><Save size={16} />{busy ? "Saving…" : "Save daily revenue"}</button>{message && <p className="mt-3 rounded-xl bg-success-soft px-3 py-2.5 text-sm text-success">{message}</p>}</div>
      <div className="rounded-2xl border border-line bg-canvas/70 p-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-ink-soft">How this day is calculated</p><div className="mt-4 space-y-3"><Calculation label="Daily logged spend" value={formatCurrency(spent)} /><Calculation label={`Revenue · $${Number(usd || 0).toLocaleString()} × ₦${Number(rate || 0).toLocaleString()}`} value={formatCurrency(revenueNgn)} /><div className="border-t border-line pt-3"><Calculation label="Net result" value={formatCurrency(result)} emphasis tone={result >= 0 ? "text-success" : "text-danger"} /></div></div><p className="mt-5 text-xs leading-5 text-ink-soft">Spend is a sum of {entries.length} daily ad log{entries.length === 1 ? "" : "s"} on {day}. Changing a spend entry automatically changes this comparison.</p></div></section>
    {fetching && <div className="flex justify-center"><Loader2 size={18} className="animate-spin text-ink-soft" /></div>}</div></AppShell>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-ink"><span>{label}</span><div className="mt-1.5 [&_.field]:w-full [&_.field]:rounded-xl [&_.field]:border [&_.field]:border-line [&_.field]:bg-canvas/50 [&_.field]:px-3 [&_.field]:py-3 [&_.field]:text-sm [&_.field]:font-normal [&_.field]:text-ink [&_.field]:outline-none [&_.field]:transition [&_.field]:focus:border-primary [&_.field]:focus:bg-white">{children}</div></label>; }
function Metric({ icon: Icon, label, value, sub, tone }: { icon: typeof DollarSign; label: string; value: string; sub?: string; tone: string }) { return <article className="app-surface p-4"><span className={`grid h-9 w-9 place-items-center rounded-xl bg-canvas ${tone}`}><Icon size={18} /></span><p className="mt-4 text-xs font-semibold text-ink-soft">{label}</p><p className={`mt-1 font-display text-xl font-extrabold tracking-tight ${tone}`}>{value}</p>{sub && <p className="mt-1 text-xs text-ink-soft">{sub}</p>}</article>; }
function Calculation({ label, value, emphasis, tone = "text-ink" }: { label: string; value: string; emphasis?: boolean; tone?: string }) { return <div className="flex items-end justify-between gap-4"><p className="text-sm text-ink-soft">{label}</p><p className={`${emphasis ? "font-display text-lg font-extrabold" : "font-semibold"} ${tone}`}>{value}</p></div>; }
